server.port=8080
#spring.datasource.url=jdbc:postgresql://supershh:dpg-d2g3sh75r7bs73ejdt0g-a.oregon-postgres.render.com/minichat_db
#spring.datasource.username=supershh
#spring.datasource.password=GxsYYBINJ9cpOD8APdbduhRnaQvhOd6s
spring.datasource.url=jdbc:postgresql://localhost:5432/minichat_db
spring.datasource.username=postgres
spring.datasource.password=yoonjin717
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# application.properties (default, ??)
#frontend.url=http://localhost:5173
# application-prod.properties (???)
frontend.url=https://my-frontend.com
